name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]  # Removed 3.7 as it's causing issues

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Changed to v4 to match the latest version

      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Manually install Django and other necessary packages (replace as needed)
        pip install Django==4.2  # Specify the required version of Django
        pip install pytest  # Example for testing dependencies, add others as necessary

    - name: Run Tests
      run: |
        python manage.py test
